<a href="https://colab.research.google.com/github/BrunoAnastacio/numpy/blob/main/11_formas_de_iniciar_uma_matriz_com_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np

In [14]:
#1 - utilizando o metodo np.array, recebendo uma lista em Python como parâmetro
v = np.array([1,2,3])

matriz = [[1,2,3],[4,5,6]]

m = np.array(matriz)

print (v)
print (m)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [15]:
#2 - também é possível inicializar um vetor Numpy à partir de uma tupla:

t = np.array((2,3,4))
print (t)

[2 3 4]


In [16]:
#3 - usando np.arange, que cria um array no melhor estilo "start, stop, step" das 'ranges' em Python
#Como parâmetros, devemos passar o número onde começa o nosso vetor, o número onde ele termina e de quantos em quantos números ele deve pular

a = np.arange(10,100,5)
b = np.arange(100,20,-20) #entendeu o que aconteceu aqui?
print (a)
print (b)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[100  80  60  40]


In [17]:
#4 - vetor de zeros: com Numpy, você pode criar um vetor prenchido apenas por zeros
z = np.zeros(100)

print (z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


In [18]:
#5 - da mesma forma, podemos criar um vetor preenchidos apenas por 'uns':
o = np.ones(100)

print(o)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


In [19]:
#6 - com a função 'eye', posso criar uma matriz onde a diagonal é composta por numeros um enquanto as demais posições são zero:
e = np.eye(8)
ee = np.eye(3)

print (e)
print (ee)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
#7 - usando 'diag', eu posso colocar qualquer valor na diagonal:
d = np.diag([1,3,5,7,9])

print (d)

[[1 0 0 0 0]
 [0 3 0 0 0]
 [0 0 5 0 0]
 [0 0 0 7 0]
 [0 0 0 0 9]]


In [21]:
#8 - também podemos criar uma matriz de booleanos
b = np.array([True,True,False,True])

print (b)

[ True  True False  True]


In [22]:
#9 - ou de strings...

s = np.array(["Python", "Java", "Kotlin"])

print (s)

['Python' 'Java' 'Kotlin']


In [23]:
#10 - o método linspace devolve um vetor igualmente distribuido de acordo com o informado no "step"
#no exemplo abaixo, temos um vetor que vai de 0 a 10, dividido em 50 partes iguais.

l = np.linspace(0, 10, 50)

print(l)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [24]:
#11 - criando uma matriz com valores aleatórios

rnd = np.random.rand(3,3,3)
print(rnd)

[[[0.85335195 0.25369801 0.46129548]
  [0.69493158 0.93891877 0.28857706]
  [0.58096479 0.37519449 0.15299963]]

 [[0.82362524 0.57273643 0.02766573]
  [0.83407615 0.73226036 0.41458584]
  [0.01610694 0.32614932 0.61936262]]

 [[0.0295057  0.1071113  0.2377057 ]
  [0.07274471 0.23223111 0.36607369]
  [0.12057887 0.05159337 0.83255393]]]
