<a href="https://colab.research.google.com/github/BrunoAnastacio/numpy/blob/main/numpy_101_exerc%C3%ADcios_de_fixa%C3%A7%C3%A3o.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#101 Numpy EXERCISES

> https://www.machinelearningplus.com/python/101-numpy-exercises-python/



### 1. Import numpy as np and see the version

In [1]:
import numpy as np #importa a lib numpy
print(np.__version__) #da um print no atributo "__version__"

1.22.4


In [2]:
#por exemplo: vamos fazer o mesmo tentando importas a lib pandas...
import pandas as pd
print(pd.__version__)

1.4.4


In [3]:
#... e a tkinter
import tkinter as tk
print(tk.__version__)

#como tkinter não tem  atributo "__version__" implementado, o código dará erro

AttributeError: ignored

2. How to create a 1D array?

In [4]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
brr = np.arange(5*5)
brr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

3. How to create a boolean array?

In [18]:
crr = np.full((3, 3), False, dtype=bool)
crr

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

4. How to extract items that satisfy a given condition from 1D array?

In [32]:
# Input
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Solution
# consigo usar uma expressão dentro dos []
arr[arr % 2 == 1]
arr

array([0, 0, 2, 0, 4, 0, 6, 0, 8, 0])

In [29]:
# por exemplo, poderia utilizar list comprehension
arr[[x for x in range(5)]]
arr

array([0, 1, 2, 3, 4])

6. How to replace items that satisfy a condition without affecting the original array?

In [33]:
arr[arr % 2 == 1] = 0
arr

array([0, 0, 2, 0, 4, 0, 6, 0, 8, 0])

In [34]:
arr[[x for x in range(5)]]  = 10
arr

array([10, 10, 10, 10, 10,  0,  6,  0,  8,  0])

7. How to reshape an array?

In [43]:
arr = np.arange(12).reshape(4,3) #(quantos novos arrays, tamanho dos novos arrays)

#lembrando que esse "a,b" tem que ser a*b = tamanho do array original

#ao setar o segundo atributo como -1 , o newshape será definido automaticamente


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
#segurança

#ia/ml/ds, dba, infra/cloud, devops 
#backend
#front, ux, mobile
#QA
#seo

8, 9. Stacking arrays

In [48]:
#verticalmente
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

#tres formas de se fazer
np.concatenate ([a,b], axis = 0)
#np.vstack([a,b])
#np.r_[a,b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [50]:
#horizontalmmente
a = np.arange(15).reshape(3,5)
b = np.repeat(1,15).reshape(3,5)

#np.concatenate([a,b], axis = 1)
np.hstack([a,b])
#np.h_[a,b]

array([[ 0,  1,  2,  3,  4,  1,  1,  1,  1,  1],
       [ 5,  6,  7,  8,  9,  1,  1,  1,  1,  1],
       [10, 11, 12, 13, 14,  1,  1,  1,  1,  1]])

10. How to generate custom sequences in numpy without hardcoding?

In [53]:
a = np.array([1,2,3])
#np.r_[np.repeat(a, 3), np.tile(a, 3)]
np.r_[np.tile(a, 4)]

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

11. How to get the common items between two python numpy arrays?

In [58]:
a = np.tile([1,4,7],5)
b = np.tile([1,3,5,7,9],9)
c = np.arange(10)
np.intersect1d(c,b)

array([1, 3, 5, 7, 9])

In [59]:
#para verificar mais de dois arrays, pdoemos utilizar a função reduce
from functools import reduce
reduce(np.intersect1d, (a,b,c))

array([1, 7])