## Como instalar?
### pip install numpy
### pip install numpy -U para atualizar a versão do pacote

In [1]:
#pip install numpy #descomentar se necessário

In [2]:
#pip install numpy -U #descomentar se necessário

## Como importar??
### import numpy as np
### use np.__version__ para confirmar a versão do pacote

In [3]:
import numpy as np

In [4]:
np.__version__

'1.18.5'

## Arrays vs Lists

In [5]:
#criando um vetor a partir de uma lista em python
a = [0,10,20,30,40] #a lista...
vetor1 = np.array(a) #transformando a lista em vetor, utilizando 'np.array'
print(vetor1)

[ 0 10 20 30 40]


In [6]:
#o vetor produzido pelo np.array é do tipo ndarray
type(vetor1)

numpy.ndarray

In [7]:
#... enquanto a lista 'a' é do tipo list
type(a)

list

In [8]:
#com uma lista, eu tenho as seguintes possibilidades:
dir(list)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [9]:
#...enquanto com um vetor do numpy, eu tenho estas possibilidades:
dir(np.array)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__text_signature__']

In [10]:
#obtendo a média dos valores inseridos no vetor
media_vetor1 = vetor1.mean()
media_vetor1

20.0

In [11]:
#realizando a soma acumulada dos itens do vetor
#aqui, o resultado é um vetor com primeiro item, o segundo, a soma do primeiro com o segundo, 
#o resultado da soma anterior com o próximo e etc...
soma_acumulada_vetor1 = vetor1.cumsum()
soma_acumulada_vetor1

array([  0,  10,  30,  60, 100], dtype=int32)

In [12]:
#valor máximo entre os itens do vetor
maximo = vetor1.max()
maximo

40

In [13]:
#valor mínimo entre os itens do vetor
minimo = vetor1.min()
minimo

0

In [14]:
#buscando um elemento no vetor a partir da sua indexação
#vamos buscar o primeiro elemento do vetor, lembrando que na maioria das linguagens, a indexação começa sempre por zero
primeiro = vetor1[0]
primeiro

0

In [15]:
#já o segundo elemento do vetor...
segundo = vetor1[1]
segundo

10

In [16]:
#use .size para obter o tamanho do vetor
tamanho = vetor1.size
tamanho

5

In [17]:
# um for básico para imprimir todos os elementos do vetor...
for v in vetor1:
    print(v)

0
10
20
30
40


In [18]:
#Sendo:
    #               vetor1 = [0,10,20,30,40]
    #soma_acumulada_vetor1 = [0,10,30,60,100]
    
#o que será que acontece se eu somar 'vetor1 + soma_acumulada_vetor1'?
    #a) os vetores serão concatenados em um só
    #b) será somado os elementos dos vetores (primeiro com primeiro, segundo com segundo, etc..)
    #c) N.d.a.
    
#Vamos ver?


vetorzao = vetor1 + soma_acumulada_vetor1
vetorzao

array([  0,  20,  50,  90, 140])

In [19]:
#mas, e pra concatenar arrays, comofas?
vetor_concatenado = np.concatenate((vetor1, soma_acumulada_vetor1, vetorzao),axis=None)
vetor_concatenado

array([  0,  10,  20,  30,  40,   0,  10,  30,  60, 100,   0,  20,  50,
        90, 140])