<a href="https://colab.research.google.com/github/BrunoAnastacio/numpy/blob/main/Opera%C3%A7%C3%B5es_com_arrays_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#vamos criar duas matrizes

a = np.arange(10)
b = np.arange(10, 20)


In [3]:
#aritimética básica com Numpy

soma = a+b
subtracao = a-b
multiplicacao = a*b
divisao = a/b

print(soma)
print(subtracao)
print(multiplicacao)
print(divisao)

[10 12 14 16 18 20 22 24 26 28]
[-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]
[  0  11  24  39  56  75  96 119 144 171]
[0.         0.09090909 0.16666667 0.23076923 0.28571429 0.33333333
 0.375      0.41176471 0.44444444 0.47368421]


In [4]:
# o que acontece se eu somar o vetor 'a' ao numero 100? Vamos verificar?
c = a+100
print(a)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[100 101 102 103 104 105 106 107 108 109]


In [5]:
#obtendo a média dos valores de um array
d = c.mean()
print(d)

104.5


In [6]:
#Ordenando elementos de um array
e = np.array([5,3,9,5,8])
f = np.sort(e)
print (f)

[3 5 5 8 9]


In [7]:
#Potenciação com vetores

#a operação abaixo cria um novo vetor com o resultado de 2 elevado a cada um dos elemento do vetor g

g = 2**f
print(f)
print (g)

[3 5 5 8 9]
[  8  32  32 256 512]


In [8]:
#Aqui acontece o contrário:
#Um novo vetor com o resultado da elevação de cada elemento do vetor ao quadrado

h = f**2
print(f)
print(h)

[3 5 5 8 9]
[ 9 25 25 64 81]


In [9]:
#para encontrar a raiz quadrada de cada elemento do vetor, basta eleva-lo à 1/2

i = h**0.5
print (i)

[3. 5. 5. 8. 9.]
